theme: jekyll-theme-minimal
logo: /sheep_double_thumbs_up.jpg/
title: Nathaniel Cortes - Resume 2026
description: Educated software engineer blending military and corporate experience as a driver of business value. Seeking software development or similar skilled positions. Contact me by email at mail {at} natecortes.com.
