theme: jekyll-theme-minimal
title: Nathaniel Cortes - Resume 2026
description: Educated software engineer blending military and corporate experience as a driver of business value. Seeking software development or similar skilled positions. 
*Phone\:* ​480-729-0157​ 
*Email\:* ​mail@natecortes.com​ 
*Web\:* ​http://resume.natecortes.com 
