theme: jekyll-theme-minimal
#logo: /placeholder_image.jpg
title: Nathaniel Cortes
description: Educated software engineer with a blend of military and corporate experience seeking software development or similar skilled positions. Contact me by email at mail {at} natecortes.com
